export const providerDomains = [
    { id: 'reanime', name: 'ReAnime', url: 'https://reanime.to' },
    { id: 'kisskh', name: 'KissKH', url: 'https://kisskh.nl' },
    { id: 'watchsomuch', name: 'WatchSoMuch', url: 'https://watchsomuch.tv' },
    { id: 'ninetv', name: 'NineTV', url: 'https://moviesapi.club' },
    { id: 'allmovieland', name: 'AllMovieland', url: 'https://allmovieland.io' },
    { id: 'animetosho', name: 'AnimeTosho', url: 'https://animetosho.xyz' },
    { id: 'nepu', name: 'Nepu', url: 'https://nepu.to' },
    { id: 'dahmermovies', name: 'DahmerMovies', url: 'https://a.111477.xyz' },
    { id: 'animepahe', name: 'AnimePahe', url: 'https://animepahe.pw' },
    { id: 'rivestream', name: 'RiveStream', url: 'https://www.rivestream.app' },
    { id: 'kickass', name: 'KickassAnime', url: 'https://kaa.lt' },
    { id: 'vidsrcxyz', name: 'VidSrcXyz', url: 'https://vidsrc-embed.su' },
    { id: 'moviebox', name: 'MovieBox', url: 'https://api.inmoviebox.com' },
    { id: 'vidrock', name: 'Vidrock', url: 'https://vidrock.ru' },
    { id: 'vidlink', name: 'Vidlink', url: 'https://vidlink.pro' },
    { id: 'vidfast', name: 'VidFast', url: 'https://vidfast.pro' },
    { id: 'videasy', name: 'VidEasy', url: 'https://api.videasy.net' },
    { id: 'cinemacity', name: 'CinemaCity', url: 'https://cinemacity.cc' },
    { id: 'hexasu', name: 'HexaSU', url: 'https://theemoviedb.hexa.su' },
    { id: 'mapple', name: 'MappleTV', url: 'https://mapple.uk' },
    { id: '2embed', name: '2Embed', url: 'https://www.2embed.cc' },
    { id: 'xpass', name: 'Xpass', url: 'https://play.xpass.top' },
    { id: 'vaplayer', name: 'Vaplayer', url: 'https://streamdata.vaplayer.ru' },
    { id: 'peachify', name: 'Peachify', url: 'https://peachify.top' },
    { id: 'anineko', name: 'AniNeko', url: 'https://anineko.to' }
];
